/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllChecks } from '../fn/aircraft-check/get-all-checks';
import { GetAllChecks$Params } from '../fn/aircraft-check/get-all-checks';

@Injectable({ providedIn: 'root' })
export class AircraftCheckService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllChecks()` */
  static readonly GetAllChecksPath = '/api/v1/aircraft-check';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllChecks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllChecks$Response(params?: GetAllChecks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getAllChecks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllChecks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllChecks(params?: GetAllChecks$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getAllChecks$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
