/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AddScheduledCheckRequest } from './models/add-scheduled-check-request';
export { AircraftCheck } from './models/aircraft-check';
export { Airplane } from './models/airplane';
export { AirplaneDto } from './models/airplane-dto';
export { ApiResponse } from './models/api-response';
export { AuthPerformedWorkDto } from './models/auth-performed-work-dto';
export { CreateReportByPeriodAndSerialNumberRequest } from './models/create-report-by-period-and-serial-number-request';
export { CreateReportByPeriodRequest } from './models/create-report-by-period-request';
export { PageResponseAirplaneDto } from './models/page-response-airplane-dto';
export { PageResponseAuthPerformedWorkDto } from './models/page-response-auth-performed-work-dto';
export { PageResponsePerformedWorkDto } from './models/page-response-performed-work-dto';
export { PageResponseScheduledCheckDto } from './models/page-response-scheduled-check-dto';
export { PerformedWork } from './models/performed-work';
export { PerformedWorkDto } from './models/performed-work-dto';
export { PerformedWorkRequest } from './models/performed-work-request';
export { ScheduledCheck } from './models/scheduled-check';
export { ScheduledCheckDto } from './models/scheduled-check-dto';
export { UpdateScheduledCheckRequest } from './models/update-scheduled-check-request';
