services:
  postgres:
    container_name: ms_pg_slq
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: keycloak
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - aircraft-net
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mail_hog_am
    ports:
      - 1025:1025
      - 8025:8025

  keycloak:
    container_name: keycloak-am
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9098:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: timur
      KC_DB_PASSWORD: timur
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    volumes:
      - ./Aircraft-Maintenance-Java-Spring-Boot-Curs/src/main/resources/keycloak/import:/opt/keycloak/data/import
      - ./Aircraft-Maintenance-Java-Spring-Boot-Curs/src/main/resources/keycloak/themes:/opt/keycloak/themes/mytheme
    command:
      -v start-dev --import-realm
    depends_on:
      - postgres
    networks:
      - aircraft-net

#  am-api:
#    container_name: am-api
#    image: am/am-api:1.0.0
#    ports:
#      - 8088:8088
#    networks:
#      - aircraft-net
#    depends_on:
#      - postgres
#      - keycloak
#
#  am-ui:
#    container_name: am-ui
#    image: am/am-ui:1.0.0
#    ports:
#      - 8080:80
#    networks:
#      - aircraft-net
#    depends_on:
#      - am-api

networks:
  aircraft-net:
    driver: bridge

volumes:
  postgres: