/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AircraftCheck } from '../../models/aircraft-check';

export interface GetAllChecks$Params {
}

export function getAllChecks(http: HttpClient, rootUrl: string, params?: GetAllChecks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AircraftCheck>>> {
  const rb = new RequestBuilder(rootUrl, getAllChecks.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AircraftCheck>>;
    })
  );
}

getAllChecks.PATH = '/api/v1/aircraft-check';
