/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddScheduledCheckRequest {
  airplaneSerialNumber: string;
  date: string;
  status: 'PLANNED' | 'PROCESSING' | 'COMPLETED' | 'CANCELED';
  type: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'OVERHAUL' | 'POST_REPAIR' | 'PRE_FLIGHT' | 'POST_FLIGHT';
}
