/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerformedWork } from '../models/performed-work';
export interface AircraftCheck {
  checkName?: string;
  id?: number;
  performedWork?: Array<PerformedWork>;
}
