/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerformedWork } from '../models/performed-work';
import { ScheduledCheck } from '../models/scheduled-check';
export interface Airplane {
  id?: number;
  model?: string;
  performedWorks?: Array<PerformedWork>;
  scheduledChecks?: Array<ScheduledCheck>;
  serialNumber?: string;
  yearOfRelease?: string;
}
