/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthPerformedWorkDto {
  completionDate?: string;
  description?: string;
  id?: number;
  result?: string;
  serialNumber?: string;
  workName?: string;
}
