/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReportByPeriodAndSerialNumberRequest {
  date1: string;
  date2?: string;
  reportFormat: string;
  serialNumber: string;
}
