/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AirplaneDto } from '../models/airplane-dto';
export interface PageResponseAirplaneDto {
  content?: Array<AirplaneDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
