/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerformedWorkDto } from '../models/performed-work-dto';
export interface PageResponsePerformedWorkDto {
  content?: Array<PerformedWorkDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
