/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerformedWorkDto {
  completionDate?: string;
  createdDate?: string;
  description?: string;
  engineerId?: string;
  result?: string;
  serialNumber?: string;
  workName?: string;
}
