/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerformedWorkRequest {
  airplaneSerialNumber: string;
  completionDate?: string;
  description?: string;
  result: 'NORMAL' | 'EXCHANGE' | 'CRASH';
  workName: string;
}
