/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScheduledCheckDto {
  date?: string;
  serialNumber?: string;
  status?: 'PLANNED' | 'PROCESSING' | 'COMPLETED' | 'CANCELED';
  type?: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'OVERHAUL' | 'POST_REPAIR' | 'PRE_FLIGHT' | 'POST_FLIGHT';
}
