/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Airplane } from '../models/airplane';
export interface ScheduledCheck {
  airplane?: Airplane;
  createdBy?: string;
  createdDate?: string;
  date?: string;
  engineerId?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  notificationSent?: boolean;
  status?: 'PLANNED' | 'PROCESSING' | 'COMPLETED' | 'CANCELED';
  type?: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'OVERHAUL' | 'POST_REPAIR' | 'PRE_FLIGHT' | 'POST_FLIGHT';
}
