/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateScheduledCheckRequest {
  date: string;
  status: 'PLANNED' | 'PROCESSING' | 'COMPLETED' | 'CANCELED';
}
