/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirplaneDto } from '../../models/airplane-dto';

export interface GetAirplaneBySerialNumber$Params {
  serialNum: string;
}

export function getAirplaneBySerialNumber(http: HttpClient, rootUrl: string, params: GetAirplaneBySerialNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<AirplaneDto>> {
  const rb = new RequestBuilder(rootUrl, getAirplaneBySerialNumber.PATH, 'get');
  if (params) {
    rb.query('serialNum', params.serialNum, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirplaneDto>;
    })
  );
}

getAirplaneBySerialNumber.PATH = '/api/v1/airplanes/airplane/by/serial-number';
