/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirplaneDto } from '../../models/airplane-dto';

export interface GetAllAirplanes$Params {
}

export function getAllAirplanes(http: HttpClient, rootUrl: string, params?: GetAllAirplanes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AirplaneDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllAirplanes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AirplaneDto>>;
    })
  );
}

getAllAirplanes.PATH = '/api/v1/airplanes';
