/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AirplaneDto } from '../../models/airplane-dto';

export interface GetAirplaneById$Params {
  airplaneId: number;
}

export function getAirplaneById(http: HttpClient, rootUrl: string, params: GetAirplaneById$Params, context?: HttpContext): Observable<StrictHttpResponse<AirplaneDto>> {
  const rb = new RequestBuilder(rootUrl, getAirplaneById.PATH, 'get');
  if (params) {
    rb.path('airplaneId', params.airplaneId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AirplaneDto>;
    })
  );
}

getAirplaneById.PATH = '/api/v1/airplanes/{airplaneId}';
