/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateReportByPeriodAndSerialNumberRequest } from '../../models/create-report-by-period-and-serial-number-request';

export interface CreateReportByPeriodAndSerialNumber$Params {
      body: CreateReportByPeriodAndSerialNumberRequest
}

export function createReportByPeriodAndSerialNumber(http: HttpClient, rootUrl: string, params: CreateReportByPeriodAndSerialNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, createReportByPeriodAndSerialNumber.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

createReportByPeriodAndSerialNumber.PATH = '/api/v1/performed-works/create-report/by/period-and-serial-number';
