/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponsePerformedWorkDto } from '../../models/page-response-performed-work-dto';

export interface GetAllWorks$Params {
  page?: number;
  size?: number;
}

export function getAllWorks(http: HttpClient, rootUrl: string, params?: GetAllWorks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponsePerformedWorkDto>> {
  const rb = new RequestBuilder(rootUrl, getAllWorks.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponsePerformedWorkDto>;
    })
  );
}

getAllWorks.PATH = '/api/v1/performed-works';
