/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseAuthPerformedWorkDto } from '../../models/page-response-auth-performed-work-dto';

export interface GetAllWorksByEngineerAuthId$Params {
  page?: number;
  size?: number;
}

export function getAllWorksByEngineerAuthId(http: HttpClient, rootUrl: string, params?: GetAllWorksByEngineerAuthId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAuthPerformedWorkDto>> {
  const rb = new RequestBuilder(rootUrl, getAllWorksByEngineerAuthId.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseAuthPerformedWorkDto>;
    })
  );
}

getAllWorksByEngineerAuthId.PATH = '/api/v1/performed-works/my-performed-work';
