/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { PerformedWorkRequest } from '../../models/performed-work-request';

export interface UpdatePerformedWork$Params {
  performedWorkId: number;
      body: PerformedWorkRequest
}

export function updatePerformedWork(http: HttpClient, rootUrl: string, params: UpdatePerformedWork$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePerformedWork.PATH, 'put');
  if (params) {
    rb.path('performedWorkId', params.performedWorkId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse>;
    })
  );
}

updatePerformedWork.PATH = '/api/v1/performed-works/my-performed-work/change/{performedWorkId}';
