/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { UpdateScheduledCheckRequest } from '../../models/update-scheduled-check-request';

export interface UpdateScheduledCheck$Params {
  scheduledCheckId: number;
      body: UpdateScheduledCheckRequest
}

export function updateScheduledCheck(http: HttpClient, rootUrl: string, params: UpdateScheduledCheck$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse>> {
  const rb = new RequestBuilder(rootUrl, updateScheduledCheck.PATH, 'put');
  if (params) {
    rb.path('scheduledCheckId', params.scheduledCheckId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse>;
    })
  );
}

updateScheduledCheck.PATH = '/api/v1/scheduled-checks/scheduled-check/change/{scheduledCheckId}';
